# Generated by Django 5.2.6 on 2025-09-18 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='favorite_genres',
            new_name='genres',
        ),
    ]
