# Generated by Django 5.2.6 on 2025-09-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_favorite_genres_userprofile_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, null=True),
        ),
    ]
